// app/layout.js (assuming you're using Next.js App Router)
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <html lang="en">
       
        <body className={inter.className}>
        <ChakraProvider>
          {children}
        
        <Footer />
        </ChakraProvider>
        </body>
      </html>
   
  );
}
